LOCATIONSERVICE_BASE_PATH: "http://location-service.perftest:8080"
RIDERSERVICE_BASE_PATH: "http://rider-service.perftest:8080"
BROADCASTSERVICE_BASE_PATH: "http://broadcast-service.perftest:8080"
OPERATIONS_SERVICE_BASE_PATH: "http://operations-service.perftest:8080"
REDIS_PRIMARY_HOST: rider-perftest-elasticache-redis.l9akz6.ng.0001.apse1.cache.amazonaws.com
REDIS_READ_HOST: rider-perftest-elasticache-redis-ro.l9akz6.ng.0001.apse1.cache.amazonaws.com