---
# Source: environment/templates/devops-config/deployment/deployment-vars-{{env}}.yml
# This file was generated at  using generator Version: 

DEPLOYMENT:
    ENV: preprod2
    NAMESPACE: preprod2
    CONFIG_FILES:
        - "src/main/resources/config/job-allocation-service.default.yaml"
        - "src/main/resources/config/job-allocation-service.preprod2.yaml"

APP:
    REPLICA: 6
    HPA:
      ENABLED: 0
      MIN_REPLICA: 3
      MAX_REPLICA: 6
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 1Gi
        LIMIT: 1536Mi
      CPU:
        REQUEST: 1
        LIMIT: 1
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/preprod2/job-allocation-service/"
